# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecret_app', '0002_auto_20170627_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='secret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_secret', to='dojosecret_app.Secret'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to='dojosecret_app.User'),
        ),
    ]
