# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DojoSecret_app', '0003_auto_20170626_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='secret_id',
            new_name='secret',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='secrets',
            old_name='user_id',
            new_name='user',
        ),
    ]
