# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('DojoSecret_app', '0004_auto_20170626_1031'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='likes',
            managers=[
                ('likesManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='likes',
            name='secret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='DojoSecret_app.Secrets'),
        ),
    ]
