# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DojoSecret_app', '0005_auto_20170626_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrets',
            name='like',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
